### ISSUE TITLE
pfx file

### ISSUE THREAD

**Issue by gexiwen** [maliming/DomainTenantResolver#1]
Hi Maliming,
Thanks for your awesome sample.

I have a question about how to generate my own pfx file for debuging.
For example, dycore.com.pfx and this domain parse to 127.0.0.1.
How do you do this? Thanks.
![image](https://user-images.githubusercontent.com/61819560/113408719-77fea080-93e2-11eb-8b67-c835e5e12aea.png)

**Comment by maliming** [comment]
hi

https://certifytheweb.com/

![image](https://user-images.githubusercontent.com/6908465/113413007-48ed2c80-93ec-11eb-8a84-bda26f0719ac.png)

![image](https://user-images.githubusercontent.com/6908465/113413087-6b7f4580-93ec-11eb-9bea-3c3ec40028e9.png)

**Comment by gexiwen** [comment]
Hi Maliming,
Thank you so much.
